#############################################################################################
#########################  Script mode  #####################################################
#############################################################################################
mode: DEBUG
#mode: PROD


#############################################################################################
####################  Settings for e-mailing ################################################
#############################################################################################
e-mailing_status: ON
# Put your e-mail and password to send mail (@gmail.com only)
msg_from:
- my_post@gmail.com:my_password

# Put list of e-mails for distribution
msg_to:
- mail_for_spam@mail.ru


#############################################################################################
####################  Settings for telegram  ################################################
#############################################################################################
telegram_status: ON
# Put your Telegram bot token here
token: 123456789:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX


# Allowed user_id and chat_id. Only users from this list could get content.
# 1)PROD
# 2)DEBUG
users:
- -xxxxxxxxxxxxx
- -xxxxxxxxxxxxx



#############################################################################################
################  Common settings for telegram and e-mailing  ###############################
#############################################################################################
# How often(in seconds) notify will be sent.
interval: 1500

# Minimum volume of trading on the BitTrex exchange in the last 24 hours in USD
24hr_Vol: 500000

# Minimum capitalization of the cryptocurrency in USD
min_Cap: 50000000



#############################################################################################
#######################  Settings for Bollinger bands  ######################################
#############################################################################################
# Number of iterations for averaging moving_average
num_avg: 4

# Number of last points for calculating the root-mean-square deviation
limit: 20

# Percentage of proximity of current price to the Bollinger line
percent: 5



#############################################################################################
#######################  Settings for Money Flow Index  #####################################
#############################################################################################
#MFI status
use_MFI: ON